/**
 * assignBinCodes.js
 * One-time script: assigns a stable BIN-XXXXXXXX code to every bin
 * that is missing one. Safe to run multiple times — skips bins that
 * already have a binCode.
 *
 * Usage:  node db/assignBinCodes.js
 */
require('dotenv').config({ path: require('path').join(__dirname, '..', '.env') });
const mongoose = require('mongoose');
const Bin = require('../models/Bin');

async function run() {
  await mongoose.connect(process.env.MONGO_URI);

  const bins = await Bin.find({ $or: [{ binCode: null }, { binCode: { $exists: false } }] });

  if (!bins.length) {
    console.log('[assignBinCodes] All bins already have a binCode. Nothing to do.');
    return;
  }

  for (const bin of bins) {
    // binCode is generated by the schema default when missing; save() triggers it
    await bin.save();
    console.log(`[assignBinCodes] ${bin.name} → ${bin.binCode}`);
  }

  console.log(`[assignBinCodes] Done. ${bins.length} bin(s) updated.`);
}

run()
  .catch(err => { console.error('[assignBinCodes] Error:', err.message); process.exitCode = 1; })
  .finally(() => mongoose.disconnect());
